services:
  - type: web
    name: seferim
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SEFERIM_SECRET
        generateValue: true
      - key: SEFERIM_DRIVER_CODE
        value: refahiye2026
      - key: SEFERIM_ADMIN_USER
        value: admin
      - key: SEFERIM_ADMIN_PASS
        value: refahiye2026
      - key: PYTHON_VERSION
        value: "3.12.0"
